style(yaml): travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -48,45 +48,60 @@ matrix:
 addons:
   apt:
     packages:
-    - python-pip
-    - python-dev
+      - python-pip
+      - python-dev
   homebrew:
     packages:
-    - ansible
-    - pre-commit
+      - ansible
+      - pre-commit
     update: true
 
 cache:
   directories:
-  - $HOME/.cache/pre-commit/
+    - $HOME/.cache/pre-commit/
 
 branches:
   only:
-  - master
-  - develop
-  - /^feature\/.*$/
-  - /^bugfix\/.*$/
-  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
+    - master
+    - develop
+    - /^feature\/.*$/
+    - /^bugfix\/.*$/
+    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
 
 before_cache:
-- rm -f $HOME/.cache/pre-commit/pre-commit.log
+  - rm -f $HOME/.cache/pre-commit/pre-commit.log
 
 before_install:
   # Update Homebrew before installation
-  - if [[ "$BREW_UPGRADE" == "yes" ]]; then brew update; fi
+  - >
+    if [[ "$BREW_UPGRADE" == "yes" ]]; then
+      brew update
+    fi
 
 install:
   # Install Ansible with Homebrew on OSX
-  - if [[ "$BREW_UPGRADE" == "yes" ]]; then brew upgrade ansible; fi
+  - >
+    if [[ "$BREW_UPGRADE" == "yes" ]]; then
+      brew upgrade ansible
+    fi
 
   # upgrade pre-commit with Homebrew
-  - if [[ "$BREW_UPGRADE" == "yes" ]]; then brew upgrade pre-commit; fi
+  - >
+    if [[ "$BREW_UPGRADE" == "yes" ]]; then
+      brew upgrade pre-commit
+    fi
 
   # Install Ansible with pip
-  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install --user ansible${ANSIBLE_VERSION}; fi
+  - >
+    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
+      pip install --user ansible${ANSIBLE_VERSION}
+    fi
 
   # Install pre-commit with pip
-  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pip install --user pre-commit; fi
+  - >
+    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
+      pip install --user pre-commit
+    fi
 
   # Check Ansible version
   - ansible --version
@@ -109,25 +124,25 @@ script:
   # Test role run
   - >
     if [[ "$FROM_PACKAGE_MANAGER" == "yes" ]]; then
-      ansible-playbook tests/test.yml -i tests/inventory --connection=local
-      -e "'gcloud_install_from_package_manager':'True'"
+      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
+        -e "'gcloud_install_from_package_manager':'True'"
     else
-      ansible-playbook tests/test.yml -i tests/inventory --connection=local
-      -e "'gcloud_install_from_package_manager':'False'"
+      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
+        -e "'gcloud_install_from_package_manager':'False'"
     fi
 
   # Test idempotence
   - >
     if [[ "$FROM_PACKAGE_MANAGER" == "yes" ]]; then
-      ansible-playbook tests/test.yml -i tests/inventory --connection=local
-      -e "'gcloud_install_from_package_manager':'True'"
-      | grep -q 'changed=0.*failed=0'
-      && (echo 'Idempotence test: pass' && exit 0)
-      || (echo 'Idempotence test: fail' && exit 1)
+      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
+      -e "'gcloud_install_from_package_manager':'True'" \
+        | grep -q 'changed=0.*failed=0' \
+        && (echo 'Idempotence test: pass' && exit 0) \
+        || (echo 'Idempotence test: fail' && exit 1)
     else
-      ansible-playbook tests/test.yml -i tests/inventory --connection=local
-      -e "'gcloud_install_from_package_manager':'False'"
-      | grep -q 'changed=0.*failed=0'
-      && (echo 'Idempotence test: pass' && exit 0)
-      || (echo 'Idempotence test: fail' && exit 1)
+      ansible-playbook tests/test.yml -i tests/inventory --connection=local \
+      -e "'gcloud_install_from_package_manager':'False'" \
+        | grep -q 'changed=0.*failed=0' \
+        && (echo 'Idempotence test: pass' && exit 0) \
+        || (echo 'Idempotence test: fail' && exit 1)
     fi
